### ISSUE TITLE
Signing document without name creates invalid ASiC XAdES signature

### ISSUE THREAD

**Issue by pkoziol** [arhs/sd-dss#11]
ASiC XAdES signature for DSSDocument with null name creates .zip file with file named "detached-file" inside (set in [ASiCService.java:633](https://github.com/arhs/sd-dss/blob/ed3d21a15978833e296d38146d3e26e000204f59/apps/dss/core/dss-document/src/main/java/eu/europa/ec/markt/dss/signature/asic/ASiCService.java#L633)). However XAdES signature reference has empty URI: `<ds:Reference Id="r-id-1" Type="" URI="">` (set in [DetachedSignatureBuilder.java:80](https://github.com/arhs/sd-dss/blob/ed3d21a15978833e296d38146d3e26e000204f59/apps/dss/core/dss-document/src/main/java/eu/europa/ec/markt/dss/signature/xades/DetachedSignatureBuilder.java#L80)).

As the result signature could not be validated, because during verification, hash.is calculated from `<asic:XAdESSignatures>...</asic:XAdESSignatures>` instead from signed document.

**Comment by Bob88640** [comment]
There is no test concerning the name. This attribute should be set in the case of ASiC container.
What is your request concerning this point? raise an exception if the name is null?

**Comment by pkoziol** [comment]
Yes, raising exception is fine. If I got exception I would notice earlier that I forgot the name.

**Comment by Bob88640** [comment]
Hi,
Please let me know if the proposed solution suits you?

**Comment by pkoziol** [comment]
Hi, I didn't test it, but it looks OK.
