### ISSUE TITLE
Stale Maven repository

### ISSUE THREAD

**Issue by rferrerasm** [arhs/sd-dss#5]
Hi, I'm a new user of the library. (I'm implementing the Spanish electronic invoicing.)

I am a bit surprised that the Maven repository only has and old version and a RC of the library.

I'd think that, as with any other Java component, the main *practical* distribution point would be a Maven repository. Though I don't know how other people typically integrate this library in their build system.

Are there any plans to update / maintain updated the Maven repository?

Thanks.

**Comment by rferrerasm** [comment]
Could you upload the final 4.3.0? Thanks.

**Comment by Bob88640** [comment]
Unfortunately the upload access to https://joinup.ec.europa.eu/nexus/ is
broken so I cannot upload the file.
I'll keep you informed hen it works again.
Bob


2015-02-05 13:51 GMT+01:00 Roberto Ferreras <notifications@github.com>:
