### ISSUE TITLE
LDAP library dependency

### ISSUE THREAD

**Issue by rferrerasm** [arhs/sd-dss#6]
Is the `dss-service` dependency on `api-ldap-client-all` obligatory / used by a majority, or it could be made optional?

I ask it because it is fairly large (4.3 mb), and may be it can be made optional so you can include it only if you really need it.

**Comment by Bob88640** [comment]
I've just replaced ConcurrentHashSet by HashSet and updated some classes. It works with all my test cases.
see: 
Please keep me informed if you encounter any errors.
