### ISSUE TITLE
Error with pdfbox 1.8.8

### ISSUE THREAD

**Issue by rferrerasm** [arhs/sd-dss#7]
FYI, in case you don't know, signing a PDF with pdfbox version 1.8.8 fails:
```
java.lang.NoSuchMethodError: org.apache.pdfbox.pdmodel.PDDocument.saveIncremental(Ljava/io/FileInputStream;Ljava/io/OutputStream;)V
```

They removed this method: https://github.com/apache/pdfbox/commit/0fe2863c3b45015241b14e1c5c88808c85611b2b

It's used in https://github.com/arhs/sd-dss/blob/master/apps/dss/core/dss-document/src/main/java/eu/europa/ec/markt/dss/signature/pdf/pdfbox/PdfBoxSignatureService.java#L214

**Comment by sidner** [comment]
I found that error yesterday as well, but for some reason on the PDFbox API, the method saveIncremental(InputStream, Outputstream) is still there....

Not only that, but I can confirm that I'm using as a dependency pdfbox version 1.8.8 and the signing is working with sd-dss. Not really sure what I did (there were some dependencies that I needed that were removed that I added back again, but it's unlikely they were the cause.
